### ISSUE TITLE
Missing Header parameter type

### ISSUE THREAD

**Issue by flaviozanda** [manusant/spark-swagger#1]
There doesn't seem to be a way to document the header parameters. I think it might be nice to add support for this feature:
For example:
```java
path("/hammer")
  .withPathParam(pathParamDescriptor) 
  .withQueryParam(queryParamDescriptor)
  .withHeaderParam(headerParamDescriptor)
```

**Comment by manusant** [comment]
Hi @flaviozanda thanks for your suggestion.
I´ll add it soon.

thanks

**Comment by flaviozanda** [comment]
Great! Looking forward to it.

**Comment by manusant** [comment]
Header, cookie and form params added to method descriptor
