### ISSUE TITLE
MethodDescriptor.Builder.withResponseAsCollection(clazz) should produce an array as return schema type.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [manusant/spark-swagger#12]
Hi! Unlike what the name suggests, method `withResponseAsCollection` in `MethodDescriptor.Builder` does not result in an array in the generated swagger as the return type for the API method in which it is defined. Instead, it generates the type for  the provided class and sets that base type to be the return type.

Swagger version: 1.0.0.48.

**Comment by manusant** [comment]
this should be ccclosed by relsease https://github.com/manusant/spark-swagger/releases/tag/v2.0.2.
Also included **responseAsMap** option

**Comment by binh-dam-ibigroup** [comment]
Thank you very much!
