### ISSUE TITLE
SparkSwagger.version() does nothing

### ISSUE THREAD

**Issue by BrentP-tmx** [manusant/spark-swagger#17]
Once SparkSwagger object has been constructed, swagger.setInfo() has already been called, so setting the version later doesn't accomplish anything. Should add SparkSwagger.of() method that lets you pass version in.

**Comment by BrentP-tmx** [comment]
Also worth noting that in the documentation, it shows a version setting in the config file, which isn't actually used anywhere.

spark-swagger {
...
  info {
...
    version = "4.0.0.0.1"
...
}

**Comment by manusant** [comment]
Hi. 
New release coming that will fix this issue.
Basically there will be an Options object/builder that can be taken as second argument of the SparkSwagger.of(...) that will provide optional configurations that takes precedence compared with confs from the config file.

```java
   Options options =  Options.defaultOptions()
                .confPath("conf/" + SparkSwagger.CONF_FILE_NAME)
                .version("1.0.2")
                .build();

        SparkSwagger.of(spark, options)
```
Also from the config file, the version can be configured at **spark-swagger..info.version** or **spark-swagger.info.project.version**

**Comment by manusant** [comment]
this should be ccclosed by relsease https://github.com/manusant/spark-swagger/releases/tag/v2.0.2
