### ISSUE TITLE
Incompatibility Between Path for Generated UI and Path for Generated Java Client Library

### ISSUE THREAD

**Issue by SubutaDan** [manusant/spark-swagger#23]
I think my difficulty is related to issue #2.

I am trying to create an endpoint with path: NAME_SPACE +  query to be used like this:
```
http://192.168.1.105:4566/cnrm/admin?action=FETCH_SETTINGS
```
although I would also OK with:
```
http://192.168.1.105:4566/cnrm/admin/?action=FETCH_SETTINGS

```
I want it to work with the generated UI and with an openapi-generator generated Java client library. I have been unable to find a way to make both work.

It seems that if I use "/" as the value for PATH  then the generated UI won't work for the method 
```
[qtp200800517-18] INFO spark.http.matching.MatcherFilter - The requested route [/cnrm/admin] has not been mapped in Spark for Accept: [application/json]
```
but the Java library generated by OpenAPI-Generator works if I omit the trailing slash from the path in my Java client code.

If, on the other hand, I use "" as the value for the path then the generated UI works but I cannot find a way to make the Java library generated by OpenAPI-Generator work.
```
[qtp614303351-21] INFO spark.http.matching.MatcherFilter - The requested route [/cnrm/admin/] has not been mapped in Spark for Accept: [*/*]
```
Perhaps the generated Java library is at fault here because it seems to add a slash to whatever path it is given.  At the same time, it seems that perhaps the resolution to issue #2 may have broken compatibility with openapi-generator's java client generator.

I would appreciate your thoughts on how to proceed.

**Comment by SubutaDan** [comment]
I should have mentioned that I think this project is excellent.  Thanks so much for making it available.

**Comment by manusant** [comment]
Yes indeed. there is an issue related with paths without parameters being wrongly formatted. Working on a new release that will fix this issue.

**Comment by manusant** [comment]
this should be ccclosed by relsease https://github.com/manusant/spark-swagger/releases/tag/v2.0.2
