### ISSUE TITLE
Expose security definition / schema

### ISSUE THREAD

**Issue by naude-r** [manusant/spark-swagger#37]
Expose security definition either in code or using the static config file.

## Expected Behavior

Generated swagger-ui allow users to login or specify an api / bearer token. Documentation is updated with usage example.

## Current Behavior

Code is available for various security schema definitions, but none of it is currently used. 

## Context

Our endpoints require authentication. UI does not allow configuring / specifying that intent.

## Your Environment

N/A

**Comment by manusant** [comment]
@naude-r thanks for the issue. I'm limited in terms of availability. Can you try to implement it and then bring a PR?
Thanks

**Comment by naude-r** [comment]
@manusant have added PR #38 to resolve this. The PR is fairly basic and may not cover all use cases. These can be addressed as and when required.

**Comment by manusant** [comment]
Release 2.0.3 is now available. @naude-r can you please provide a peace of doc on how to provide the security definitions?

**Comment by naude-r** [comment]
@manusant sure. looks like you already updated the readme? do you require anything else?

**Comment by manusant** [comment]
> @manusant sure. looks like you already updated the readme? do you require anything else?

Ya i finally had some time on Friday and i did some improvements and implemented other features like HeaderDescriptor and CookieDescriptor for methods in the endpoints. I also fixed another issue when resolving configs from non relative paths.
Please check the latest version on the updated readme.

Thanks for the contribution.
