### ISSUE TITLE
Console Error: Required parameter undefined is not provided in a POST request

### ISSUE THREAD

**Issue by liatru** [manusant/spark-swagger#4]
A GET request works as expected, but a POST request cause a console error in the UI: 
```
system.js:461 Error: Required parameter undefined is not provided
    at index.js:1
    at Array.forEach (<anonymous>)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:237
    at utils.js:121
    at bindActionCreators.js:3
    at wrap-actions.js:14
    at Object.r (system.js:173)
    at Object.executeRequest (system.js:458)
    at actions.js:276
 ```

This is the code itself:
```java
restApi.endpoint(endpointPath("/")
                .withDescription("description"), (q, a) -> {})

                .get(path("/alive")
                        .withDescription("check connectivity")
                        .withGenericResponse(), (request, response) -> "OK")

                .post(path("/init")
                        .withDescription("init")
                        .withRequestType(InitRequest.class)
                        .withGenericResponse(), (req, res) -> "OK")
```

Maybe because the body param is missing a name? 
https://github.com/swagger-api/swagger-ui/issues/965

**Comment by mehuljariwala** [comment]
check the route page.

**Comment by mehuljariwala** [comment]
I guess you are missing some parameters in route page

**Comment by Fabolo12** [comment]
Please tell me, did you find a solution to the problem? Faced the exact same situation.

**Comment by mehuljariwala** [comment]
@Fabolo12  Check your route.js file swagger documentation you miss a match with something.

**Comment by Fabolo12** [comment]
@mehuljariwala sorry, I'm new in swagger, where I can find this file? These are all files which generated by lib
![image](https://user-images.githubusercontent.com/18196757/76211289-92ca0a00-620e-11ea-8b1a-8c53d324c25f.png)
And how can I understand what exactly I missed?

**Comment by se-unrc** [comment]
Somebody has some tip for this? I'm getting the same issue...

this is my code 
```
post(
                path("")
                    .withDescription("Create a new Employee")
                    .withRequestType(Employee.class)
                    .withResponseType(Employee.class),
                (req, res) -> {
                    Map<String, Object> bodyParams = new Gson().fromJson(req.body(), Map.class);        

                    Employee e = new Employee();
                    e.fromMap(bodyParams);
                    e.saveIt();
                    return e.toJson(true);
                }
            );
```

I see in the generated `swagger-spec.js `
```
"post": {
                "description": "Create a new Employee",
                "parameters": [
                    {
                        "description": "Body object description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                ],
```

and the reference is

```
"definitions": {
        "Employee": {
            "type": "object"
        }
    },
```

do I need to define better the employee definition? how so? 

When I run the check out in the swagger-ui I see an error in the javascript console

```
system.js:461 Error: Required parameter undefined is not provided
    at index.js:1
    at Array.forEach (<anonymous>)
    at Object.o [as buildRequest] (index.js:1)
    at actions.js:237
    at Object.dispatch (utils.js:121)
```

I think that it's related to swagger-api/swagger-ui#965

Not sure what is `route.js` neither, could somebody explain me that?

**Comment by se-unrc** [comment]
Sorry I was able to get the proper definition. My model inherit from Model from `javalite.activejdbc.Model` and it was not exposing the attributes, I've declared some attributes explicitly in the model and now I can see them in the definition section.

However I still get `system.js:461 Error: Required parameter undefined is not provided` when try to use it from swagger-ui

**Comment by se-unrc** [comment]
sorry too much noise here. I've realised what is the error now, in the parameter section of the path there is missing the `name` attribute. That's why we see `undefined` in `Error: Required parameter undefined is not provided`.

If I edit manually the `post -> parameters` and a I  add `"name": "body"` there, everything works properly. Now. I'm wondering how can I do to force create It? 🤔

```"post": {
                "description": "Create a new Employee",
                "parameters": [
                    {
                        "description": "Body object description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/Employee"
                        }
                    }
                },
                "tags": [
                    "employees"
                ]
            }```

**Comment by se-unrc** [comment]
I wonder if missing a `requestBody.name("body");` in
https://github.com/manusant/spark-swagger/blob/master/src/main/java/io/github/manusant/ss/Swagger.java#L491 will solve the problem. I'll try to do it and if it works I'll try a PR.

**Comment by manusant** [comment]
this should be closed by relsease https://github.com/manusant/spark-swagger/releases/tag/v2.0.2
