### ISSUE TITLE
SparkSwagger requires host IP address and (if localhost) port in conf file

### ISSUE THREAD

**Issue by johnmgithub** [manusant/spark-swagger#46]
The SparkSwagger conf file has to provide host info and, if the host is localhost, it also has to provide the port. 

The example template file uses host = "localhost" without a port, so fails on startup
The host and port are specified when starting the Spark service, why doesn't SparkSwagger get the info from the service rather than the conf file?

**Comment by johnmgithub** [comment]
It seems Spark isn't happy providing the port number before routes have been mapped, so I have passed it in via an extended SparkSwagger Options class and modified SparkSwagger  to pick it up from there.

**Comment by manusant** [comment]
Hi @johnmgithub  first of sorry for the late response. I'm happy that you managed to fix it.
If you don't mind, please provide a PR with your fix and i can release it and avoid other people to face the same issue.

Thanks in advance

**Comment by johnmgithub** [comment]
No apology required, this project has been hugely helpful. I'm not sure how to go about making a pull request, but the changes were minor. I modified getHost to accept a port:

```
    private String getHost(Integer port) {
        String host = this.config.getString("spark-swagger.host");
        if (host == null) {
            throw new IllegalArgumentException("Host is required");
        } else if (host.contains("localhost")) {
            String[] hostParts = host.split(":");
            if (hostParts.length != 2){
                host += ":" + port;
            }else{
                host = IpResolver.resolvePublicIp() + ":" + hostParts[1];
            }
        }
        log.debug("Spark-Swagger: Host resolved to {}", host);
        return host;
    }

```

and changed the constructor to get the port from Options, where I just added an Integer port field:

```
    private SparkSwagger(final Service spark, final Options options) {
        this.spark = spark;
        this.options = options == null ? Options.defaultOptions().build() : options;
        this.swagger = new Swagger();
        this.config = getConfig(options);
        this.apiPath = this.config.getString("spark-swagger.basePath");
        this.swagger.setBasePath(this.apiPath);
        this.swagger.setExternalDocs(ExternalDocs.newBuilder().build());
        this.swagger.setHost(getHost(options.getPort()));
        this.swagger.setInfo(getInfo());
        configDocRoute();
    }

```
