### ISSUE TITLE
Can't add dependency  io.github.manusant:spark-swagger:2.0.8

### ISSUE THREAD

**Issue by GabyZu** [manusant/spark-swagger#50]
##Unable to add dependency io.github.manusant:spark-swagger:2.0.8. 

After following the instructions in the Readme, I am not able to add dependency io.github.manusant:spark-swagger:2.0.8. I get error "Could not find io.github.manusant:spark-swagger:2.0.8."

## Context

Trying to add Swagger to a Spark application so that I am able to obtain the yaml/json file with all the list of endpoints. This will us to setup a Postman collection that we can use for automation testing.

## Environment

-Gradle 8.0.2
-Windows10
-Java8,11,17

**Comment by manusant** [comment]
Hey @GabyZu, sorry for the delay. Did you configured the credentials to access the github packages? 
You should be able to get it without issues.
